package com.resumeiq.service;

import com.resumeiq.dto.response.AnalysisResponse;
import com.resumeiq.dto.response.GrammarIssue;
import com.resumeiq.dto.response.SectionCompletenessResult;
import com.resumeiq.entity.AnalysisResult;
import com.resumeiq.exception.ResourceNotFoundException;
import com.resumeiq.repository.AnalysisResultRepository;
import lombok.RequiredArgsConstructor;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class ReportGenerationService {

    private final AnalysisResultRepository analysisResultRepository;
    private final AnalysisService analysisService;

    private static final float MARGIN = 50f;
    private static final float PAGE_WIDTH = PDRectangle.A4.getWidth();
    private static final float PAGE_HEIGHT = PDRectangle.A4.getHeight();
    private static final float CONTENT_W = PAGE_WIDTH - 2 * MARGIN;

    @Transactional(readOnly = true)
    public byte[] generateReport(UUID analysisId) throws IOException {
        AnalysisResult entity = analysisResultRepository.findById(analysisId)
                .orElseThrow(() -> new ResourceNotFoundException("AnalysisResult", analysisId.toString()));

        AnalysisResponse analysis = analysisService.buildResponseFromEntity(entity);

        try (PDDocument doc = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.A4);
            doc.addPage(page);

            PDType1Font bold = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            PDType1Font regular = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

            try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {
                float y = PAGE_HEIGHT - MARGIN;

                // Title
                y = writeText(cs, bold, 20, MARGIN, y, "ResumeIQ Analysis Report");
                y -= 6;
                y = writeText(cs, regular, 10, MARGIN, y, "Generated by ResumeIQ | resumeiq.com");
                y -= 4;
                drawLine(cs, MARGIN, y, PAGE_WIDTH - MARGIN, y);
                y -= 20;

                // Overall Score
                y = writeText(cs, bold, 16, MARGIN, y,
                        String.format("Overall Score: %.1f / 100", analysis.overallScore()));
                y -= 18;

                // Score breakdown
                y = writeText(cs, bold, 12, MARGIN, y, "Score Breakdown");
                y -= 4;
                drawLine(cs, MARGIN, y, PAGE_WIDTH - MARGIN, y);
                y -= 14;

                y = writeScoreLine(cs, regular, bold, MARGIN, y,
                        "ATS Compatibility", analysis.atsScore(), 100);

                if (analysis.readability() != null) {
                    y = writeScoreLine(cs, regular, bold, MARGIN, y,
                            "Readability (Flesch)", analysis.readability().fleschReadingEase(), 100);
                }
                if (analysis.sectionCompleteness() != null) {
                    y = writeScoreLine(cs, regular, bold, MARGIN, y,
                            "Section Completeness", analysis.sectionCompleteness().completenessScore(), 100);
                }
                if (analysis.actionVerbs() != null) {
                    y = writeScoreLine(cs, regular, bold, MARGIN, y,
                            "Action Verb Quality", analysis.actionVerbs().score(), 100);
                }
                if (analysis.achievements() != null) {
                    y = writeScoreLine(cs, regular, bold, MARGIN, y,
                            "Quantifiable Achievements", analysis.achievements().score(), 100);
                }
                y -= 12;

                // Sections present
                if (analysis.sectionCompleteness() != null) {
                    y = writeText(cs, bold, 12, MARGIN, y, "Sections Detected");
                    y -= 4;
                    drawLine(cs, MARGIN, y, PAGE_WIDTH - MARGIN, y);
                    y -= 14;

                    SectionCompletenessResult sc = analysis.sectionCompleteness();
                    y = writeSectionFlag(cs, regular, MARGIN, y, "Contact Info", sc.contact());
                    y = writeSectionFlag(cs, regular, MARGIN, y, "Summary / Objective", sc.summary());
                    y = writeSectionFlag(cs, regular, MARGIN, y, "Experience", sc.experience());
                    y = writeSectionFlag(cs, regular, MARGIN, y, "Education", sc.education());
                    y = writeSectionFlag(cs, regular, MARGIN, y, "Skills", sc.skills());
                    y = writeSectionFlag(cs, regular, MARGIN, y, "Projects", sc.projects());
                    y = writeSectionFlag(cs, regular, MARGIN, y, "Certifications", sc.certifications());
                    y -= 12;
                }

                // Top issues
                if (analysis.grammarIssues() != null && !analysis.grammarIssues().isEmpty()) {
                    y = writeText(cs, bold, 12, MARGIN, y,
                            "Top Improvement Areas (" + analysis.grammarIssues().size() + " issues)");
                    y -= 4;
                    drawLine(cs, MARGIN, y, PAGE_WIDTH - MARGIN, y);
                    y -= 14;

                    int shown = 0;
                    for (GrammarIssue issue : analysis.grammarIssues()) {
                        if (shown++ >= 5 || y < 80) break;
                        String text = "• [" + issue.type() + "] " + issue.suggestion();
                        y = writeWrappedText(cs, regular, 10, MARGIN, y, text, CONTENT_W);
                        y -= 4;
                    }
                }

                // Achievements sample
                if (analysis.achievements() != null && !analysis.achievements().examples().isEmpty() && y > 120) {
                    y -= 8;
                    y = writeText(cs, bold, 12, MARGIN, y, "Quantifiable Achievements Found");
                    y -= 4;
                    drawLine(cs, MARGIN, y, PAGE_WIDTH - MARGIN, y);
                    y -= 14;

                    int shown = 0;
                    for (String ex : analysis.achievements().examples()) {
                        if (shown++ >= 3 || y < 80) break;
                        y = writeWrappedText(cs, regular, 10, MARGIN, y, "• " + ex, CONTENT_W);
                        y -= 4;
                    }
                }

                // Footer
                drawLine(cs, MARGIN, 40, PAGE_WIDTH - MARGIN, 40);
                writeText(cs, regular, 9, MARGIN, 28,
                        "Analysis ID: " + analysisId + "  |  ResumeIQ  |  resumeiq.com");
            }

            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            doc.save(baos);
            return baos.toByteArray();
        }
    }

    // Package-private so AnalysisService can call it for buildResponseFromEntity
    AnalysisResponse buildResponseFromEntity(com.resumeiq.entity.AnalysisResult entity) {
        return analysisService.buildResponseFromEntity(entity);
    }

    private float writeText(PDPageContentStream cs, PDType1Font font, float size,
                            float x, float y, String text) throws IOException {
        cs.beginText();
        cs.setFont(font, size);
        cs.newLineAtOffset(x, y);
        cs.showText(sanitize(text));
        cs.endText();
        return y - size - 4;
    }

    private float writeScoreLine(PDPageContentStream cs, PDType1Font regular, PDType1Font bold,
                                 float x, float y, String label, double score, double max)
            throws IOException {
        String line = String.format("%-30s %.1f / %.0f", label, score, max);
        cs.beginText();
        cs.setFont(regular, 11);
        cs.newLineAtOffset(x, y);
        cs.showText(sanitize(line));
        cs.endText();
        return y - 16;
    }

    private float writeSectionFlag(PDPageContentStream cs, PDType1Font font,
                                   float x, float y, String label, boolean present)
            throws IOException {
        String symbol = present ? "✓" : "✗";
        // PDFBox Type1 fonts don't support ✓✗; using [Y]/[N] instead
        String line = (present ? "[Y] " : "[N] ") + label;
        cs.beginText();
        cs.setFont(font, 11);
        cs.newLineAtOffset(x, y);
        cs.showText(sanitize(line));
        cs.endText();
        return y - 15;
    }

    private float writeWrappedText(PDPageContentStream cs, PDType1Font font, float size,
                                   float x, float y, String text, float maxWidth)
            throws IOException {
        String[] words = text.split(" ");
        StringBuilder line = new StringBuilder();
        for (String word : words) {
            String candidate = line.isEmpty() ? word : line + " " + word;
            float width = font.getStringWidth(candidate) / 1000 * size;
            if (width > maxWidth && !line.isEmpty()) {
                writeText(cs, font, size, x, y, line.toString());
                y -= size + 3;
                line = new StringBuilder(word);
            } else {
                line = new StringBuilder(candidate);
            }
        }
        if (!line.isEmpty()) {
            writeText(cs, font, size, x, y, line.toString());
            y -= size + 3;
        }
        return y;
    }

    private void drawLine(PDPageContentStream cs, float x1, float y1, float x2, float y2)
            throws IOException {
        cs.moveTo(x1, y1);
        cs.lineTo(x2, y2);
        cs.stroke();
    }

    private String sanitize(String text) {
        if (text == null) return "";
        return text.replaceAll("[^\\x20-\\x7E]", "?");
    }
}